// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

package com.flydean.tutorial.protos;

public interface StudentListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.flydean.StudentList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.flydean.Student student = 1;</code>
   */
  java.util.List<com.flydean.tutorial.protos.Student> 
      getStudentList();
  /**
   * <code>repeated .com.flydean.Student student = 1;</code>
   */
  com.flydean.tutorial.protos.Student getStudent(int index);
  /**
   * <code>repeated .com.flydean.Student student = 1;</code>
   */
  int getStudentCount();
  /**
   * <code>repeated .com.flydean.Student student = 1;</code>
   */
  java.util.List<? extends com.flydean.tutorial.protos.StudentOrBuilder> 
      getStudentOrBuilderList();
  /**
   * <code>repeated .com.flydean.Student student = 1;</code>
   */
  com.flydean.tutorial.protos.StudentOrBuilder getStudentOrBuilder(
      int index);
}
