// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

package com.flydean.tutorial.protos;

public final class StudentListProtos {
  private StudentListProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_flydean_Student_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_flydean_Student_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_flydean_Student_PhoneNumber_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_flydean_Student_PhoneNumber_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_flydean_StudentList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_flydean_StudentList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rstudent.proto\022\013com.flydean\"\233\002\n\007Student" +
      "\022\021\n\004name\030\001 \001(\tH\000\210\001\001\022\017\n\002id\030\002 \001(\005H\001\210\001\001\022\022\n\005" +
      "email\030\003 \001(\tH\002\210\001\001\0220\n\006phones\030\004 \003(\0132 .com.f" +
      "lydean.Student.PhoneNumber\032i\n\013PhoneNumbe" +
      "r\022\023\n\006number\030\001 \001(\tH\000\210\001\001\0221\n\004type\030\002 \001(\0162\036.c" +
      "om.flydean.Student.PhoneTypeH\001\210\001\001B\t\n\007_nu" +
      "mberB\007\n\005_type\"!\n\tPhoneType\022\n\n\006MOBILE\020\000\022\010" +
      "\n\004HOME\020\001B\007\n\005_nameB\005\n\003_idB\010\n\006_email\"4\n\013St" +
      "udentList\022%\n\007student\030\001 \003(\0132\024.com.flydean" +
      ".StudentB2\n\033com.flydean.tutorial.protosB" +
      "\021StudentListProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_flydean_Student_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_flydean_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_flydean_Student_descriptor,
        new java.lang.String[] { "Name", "Id", "Email", "Phones", "Name", "Id", "Email", });
    internal_static_com_flydean_Student_PhoneNumber_descriptor =
      internal_static_com_flydean_Student_descriptor.getNestedTypes().get(0);
    internal_static_com_flydean_Student_PhoneNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_flydean_Student_PhoneNumber_descriptor,
        new java.lang.String[] { "Number", "Type", "Number", "Type", });
    internal_static_com_flydean_StudentList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_flydean_StudentList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_flydean_StudentList_descriptor,
        new java.lang.String[] { "Student", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
