// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

package com.flydean.tutorial.protos;

/**
 * Protobuf type {@code com.flydean.StudentList}
 */
public final class StudentList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.flydean.StudentList)
    StudentListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StudentList.newBuilder() to construct.
  private StudentList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StudentList() {
    student_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StudentList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StudentList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              student_ = new java.util.ArrayList<com.flydean.tutorial.protos.Student>();
              mutable_bitField0_ |= 0x00000001;
            }
            student_.add(
                input.readMessage(com.flydean.tutorial.protos.Student.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        student_ = java.util.Collections.unmodifiableList(student_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.flydean.tutorial.protos.StudentListProtos.internal_static_com_flydean_StudentList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.flydean.tutorial.protos.StudentListProtos.internal_static_com_flydean_StudentList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.flydean.tutorial.protos.StudentList.class, com.flydean.tutorial.protos.StudentList.Builder.class);
  }

  public static final int STUDENT_FIELD_NUMBER = 1;
  private java.util.List<com.flydean.tutorial.protos.Student> student_;
  /**
   * <code>repeated .com.flydean.Student student = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.flydean.tutorial.protos.Student> getStudentList() {
    return student_;
  }
  /**
   * <code>repeated .com.flydean.Student student = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.flydean.tutorial.protos.StudentOrBuilder> 
      getStudentOrBuilderList() {
    return student_;
  }
  /**
   * <code>repeated .com.flydean.Student student = 1;</code>
   */
  @java.lang.Override
  public int getStudentCount() {
    return student_.size();
  }
  /**
   * <code>repeated .com.flydean.Student student = 1;</code>
   */
  @java.lang.Override
  public com.flydean.tutorial.protos.Student getStudent(int index) {
    return student_.get(index);
  }
  /**
   * <code>repeated .com.flydean.Student student = 1;</code>
   */
  @java.lang.Override
  public com.flydean.tutorial.protos.StudentOrBuilder getStudentOrBuilder(
      int index) {
    return student_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < student_.size(); i++) {
      output.writeMessage(1, student_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < student_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, student_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.flydean.tutorial.protos.StudentList)) {
      return super.equals(obj);
    }
    com.flydean.tutorial.protos.StudentList other = (com.flydean.tutorial.protos.StudentList) obj;

    if (!getStudentList()
        .equals(other.getStudentList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getStudentCount() > 0) {
      hash = (37 * hash) + STUDENT_FIELD_NUMBER;
      hash = (53 * hash) + getStudentList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.flydean.tutorial.protos.StudentList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.flydean.tutorial.protos.StudentList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.flydean.tutorial.protos.StudentList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.flydean.tutorial.protos.StudentList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.flydean.tutorial.protos.StudentList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.flydean.tutorial.protos.StudentList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.flydean.tutorial.protos.StudentList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.flydean.tutorial.protos.StudentList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.flydean.tutorial.protos.StudentList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.flydean.tutorial.protos.StudentList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.flydean.tutorial.protos.StudentList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.flydean.tutorial.protos.StudentList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.flydean.tutorial.protos.StudentList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.flydean.StudentList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.flydean.StudentList)
      com.flydean.tutorial.protos.StudentListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.flydean.tutorial.protos.StudentListProtos.internal_static_com_flydean_StudentList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.flydean.tutorial.protos.StudentListProtos.internal_static_com_flydean_StudentList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.flydean.tutorial.protos.StudentList.class, com.flydean.tutorial.protos.StudentList.Builder.class);
    }

    // Construct using com.flydean.tutorial.protos.StudentList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getStudentFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (studentBuilder_ == null) {
        student_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        studentBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.flydean.tutorial.protos.StudentListProtos.internal_static_com_flydean_StudentList_descriptor;
    }

    @java.lang.Override
    public com.flydean.tutorial.protos.StudentList getDefaultInstanceForType() {
      return com.flydean.tutorial.protos.StudentList.getDefaultInstance();
    }

    @java.lang.Override
    public com.flydean.tutorial.protos.StudentList build() {
      com.flydean.tutorial.protos.StudentList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.flydean.tutorial.protos.StudentList buildPartial() {
      com.flydean.tutorial.protos.StudentList result = new com.flydean.tutorial.protos.StudentList(this);
      int from_bitField0_ = bitField0_;
      if (studentBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          student_ = java.util.Collections.unmodifiableList(student_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.student_ = student_;
      } else {
        result.student_ = studentBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.flydean.tutorial.protos.StudentList) {
        return mergeFrom((com.flydean.tutorial.protos.StudentList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.flydean.tutorial.protos.StudentList other) {
      if (other == com.flydean.tutorial.protos.StudentList.getDefaultInstance()) return this;
      if (studentBuilder_ == null) {
        if (!other.student_.isEmpty()) {
          if (student_.isEmpty()) {
            student_ = other.student_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureStudentIsMutable();
            student_.addAll(other.student_);
          }
          onChanged();
        }
      } else {
        if (!other.student_.isEmpty()) {
          if (studentBuilder_.isEmpty()) {
            studentBuilder_.dispose();
            studentBuilder_ = null;
            student_ = other.student_;
            bitField0_ = (bitField0_ & ~0x00000001);
            studentBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getStudentFieldBuilder() : null;
          } else {
            studentBuilder_.addAllMessages(other.student_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.flydean.tutorial.protos.StudentList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.flydean.tutorial.protos.StudentList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.flydean.tutorial.protos.Student> student_ =
      java.util.Collections.emptyList();
    private void ensureStudentIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        student_ = new java.util.ArrayList<com.flydean.tutorial.protos.Student>(student_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.flydean.tutorial.protos.Student, com.flydean.tutorial.protos.Student.Builder, com.flydean.tutorial.protos.StudentOrBuilder> studentBuilder_;

    /**
     * <code>repeated .com.flydean.Student student = 1;</code>
     */
    public java.util.List<com.flydean.tutorial.protos.Student> getStudentList() {
      if (studentBuilder_ == null) {
        return java.util.Collections.unmodifiableList(student_);
      } else {
        return studentBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.flydean.Student student = 1;</code>
     */
    public int getStudentCount() {
      if (studentBuilder_ == null) {
        return student_.size();
      } else {
        return studentBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.flydean.Student student = 1;</code>
     */
    public com.flydean.tutorial.protos.Student getStudent(int index) {
      if (studentBuilder_ == null) {
        return student_.get(index);
      } else {
        return studentBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.flydean.Student student = 1;</code>
     */
    public Builder setStudent(
        int index, com.flydean.tutorial.protos.Student value) {
      if (studentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentIsMutable();
        student_.set(index, value);
        onChanged();
      } else {
        studentBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.flydean.Student student = 1;</code>
     */
    public Builder setStudent(
        int index, com.flydean.tutorial.protos.Student.Builder builderForValue) {
      if (studentBuilder_ == null) {
        ensureStudentIsMutable();
        student_.set(index, builderForValue.build());
        onChanged();
      } else {
        studentBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.flydean.Student student = 1;</code>
     */
    public Builder addStudent(com.flydean.tutorial.protos.Student value) {
      if (studentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentIsMutable();
        student_.add(value);
        onChanged();
      } else {
        studentBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.flydean.Student student = 1;</code>
     */
    public Builder addStudent(
        int index, com.flydean.tutorial.protos.Student value) {
      if (studentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentIsMutable();
        student_.add(index, value);
        onChanged();
      } else {
        studentBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.flydean.Student student = 1;</code>
     */
    public Builder addStudent(
        com.flydean.tutorial.protos.Student.Builder builderForValue) {
      if (studentBuilder_ == null) {
        ensureStudentIsMutable();
        student_.add(builderForValue.build());
        onChanged();
      } else {
        studentBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.flydean.Student student = 1;</code>
     */
    public Builder addStudent(
        int index, com.flydean.tutorial.protos.Student.Builder builderForValue) {
      if (studentBuilder_ == null) {
        ensureStudentIsMutable();
        student_.add(index, builderForValue.build());
        onChanged();
      } else {
        studentBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.flydean.Student student = 1;</code>
     */
    public Builder addAllStudent(
        java.lang.Iterable<? extends com.flydean.tutorial.protos.Student> values) {
      if (studentBuilder_ == null) {
        ensureStudentIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, student_);
        onChanged();
      } else {
        studentBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.flydean.Student student = 1;</code>
     */
    public Builder clearStudent() {
      if (studentBuilder_ == null) {
        student_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        studentBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.flydean.Student student = 1;</code>
     */
    public Builder removeStudent(int index) {
      if (studentBuilder_ == null) {
        ensureStudentIsMutable();
        student_.remove(index);
        onChanged();
      } else {
        studentBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.flydean.Student student = 1;</code>
     */
    public com.flydean.tutorial.protos.Student.Builder getStudentBuilder(
        int index) {
      return getStudentFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.flydean.Student student = 1;</code>
     */
    public com.flydean.tutorial.protos.StudentOrBuilder getStudentOrBuilder(
        int index) {
      if (studentBuilder_ == null) {
        return student_.get(index);  } else {
        return studentBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.flydean.Student student = 1;</code>
     */
    public java.util.List<? extends com.flydean.tutorial.protos.StudentOrBuilder> 
         getStudentOrBuilderList() {
      if (studentBuilder_ != null) {
        return studentBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(student_);
      }
    }
    /**
     * <code>repeated .com.flydean.Student student = 1;</code>
     */
    public com.flydean.tutorial.protos.Student.Builder addStudentBuilder() {
      return getStudentFieldBuilder().addBuilder(
          com.flydean.tutorial.protos.Student.getDefaultInstance());
    }
    /**
     * <code>repeated .com.flydean.Student student = 1;</code>
     */
    public com.flydean.tutorial.protos.Student.Builder addStudentBuilder(
        int index) {
      return getStudentFieldBuilder().addBuilder(
          index, com.flydean.tutorial.protos.Student.getDefaultInstance());
    }
    /**
     * <code>repeated .com.flydean.Student student = 1;</code>
     */
    public java.util.List<com.flydean.tutorial.protos.Student.Builder> 
         getStudentBuilderList() {
      return getStudentFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.flydean.tutorial.protos.Student, com.flydean.tutorial.protos.Student.Builder, com.flydean.tutorial.protos.StudentOrBuilder> 
        getStudentFieldBuilder() {
      if (studentBuilder_ == null) {
        studentBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.flydean.tutorial.protos.Student, com.flydean.tutorial.protos.Student.Builder, com.flydean.tutorial.protos.StudentOrBuilder>(
                student_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        student_ = null;
      }
      return studentBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.flydean.StudentList)
  }

  // @@protoc_insertion_point(class_scope:com.flydean.StudentList)
  private static final com.flydean.tutorial.protos.StudentList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.flydean.tutorial.protos.StudentList();
  }

  public static com.flydean.tutorial.protos.StudentList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StudentList>
      PARSER = new com.google.protobuf.AbstractParser<StudentList>() {
    @java.lang.Override
    public StudentList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StudentList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StudentList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StudentList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.flydean.tutorial.protos.StudentList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

