// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

package com.flydean.tutorial.protos;

public interface StudentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.flydean.Student)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 id = 2;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>int32 id = 2;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string email = 3;</code>
   * @return Whether the email field is set.
   */
  boolean hasEmail();
  /**
   * <code>string email = 3;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 3;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>repeated .com.flydean.Student.PhoneNumber phones = 4;</code>
   */
  java.util.List<com.flydean.tutorial.protos.Student.PhoneNumber> 
      getPhonesList();
  /**
   * <code>repeated .com.flydean.Student.PhoneNumber phones = 4;</code>
   */
  com.flydean.tutorial.protos.Student.PhoneNumber getPhones(int index);
  /**
   * <code>repeated .com.flydean.Student.PhoneNumber phones = 4;</code>
   */
  int getPhonesCount();
  /**
   * <code>repeated .com.flydean.Student.PhoneNumber phones = 4;</code>
   */
  java.util.List<? extends com.flydean.tutorial.protos.Student.PhoneNumberOrBuilder> 
      getPhonesOrBuilderList();
  /**
   * <code>repeated .com.flydean.Student.PhoneNumber phones = 4;</code>
   */
  com.flydean.tutorial.protos.Student.PhoneNumberOrBuilder getPhonesOrBuilder(
      int index);
}
